name: "Push to BalenaCloud"
branding:
  color: "yellow"
  icon: "box"
description: "Push your code to BalenaCloud using balena-cli"
inputs:
  api-token:
    description: "BalenaCloud API Key"
    required: true
  fleet-name:
    description: "The name of the BalenaCloud Fleet that you'll be pushing to"
    required: true
  docker-image-name:
    description: "The name of the local Docker image that you'll be pushing to BalenaCloud"
    required: true
  application-path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    default: "."
  version:
    description: "The version of the release being deployed"
    default: "0.0.0"
  draft:
    description: "Mark as draft release"
    required: false
    default: "false"
  registry-secrets-yaml:
    description: "Optional. Registry secrets in YAML format. Takes precedence over other registry inputs."
    required: false
  registry-secrets-json:
    description: "Optional. Registry secrets in JSON format. Takes precedence over YAML and other registry inputs."
    required: false
  registry-urls:
    description: "Optional. Comma-separated list of registry URLs. Use empty string for Docker Hub, 'nvcr.io' for NVIDIA registry."
    required: false
  registry-usernames:
    description: "Optional. Comma-separated list of usernames corresponding to registry URLs."
    required: false
  registry-passwords:
    description: "Optional. Comma-separated list of passwords/tokens corresponding to registry URLs."
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    API_TOKEN: ${{ inputs.api-token }}
    APPLICATION_PATH: ${{ inputs.application-path }}
    FLEET_NAME: ${{ inputs.fleet-name }}
    DOCKER_IMAGE_NAME: ${{ inputs.docker-image-name }}
    VERSION: ${{ inputs.version }}
    DRAFT: ${{ inputs.draft }}
    REGISTRY_SECRETS_YAML: ${{ inputs.registry-secrets-yaml }}
    REGISTRY_SECRETS_JSON: ${{ inputs.registry-secrets-json }}
    REGISTRY_URLS: ${{ inputs.registry-urls }}
    REGISTRY_USERNAMES: ${{ inputs.registry-usernames }}
    REGISTRY_PASSWORDS: ${{ inputs.registry-passwords }}
